// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDiszpecser.Data;

namespace WebDiszpecser.Migrations
{
    [DbContext(typeof(FuvarozasDbContext))]
    partial class FuvarozasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebDiszpecser.Models.Fuvar", b =>
                {
                    b.Property<int>("FuvarID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BerakoCim")
                        .IsRequired();

                    b.Property<string>("Feladat")
                        .IsRequired();

                    b.Property<int>("GepjarmuID");

                    b.Property<DateTime>("IndulasIdeje");

                    b.Property<string>("KirakoCim")
                        .IsRequired();

                    b.Property<int>("SoforID");

                    b.HasKey("FuvarID");

                    b.HasIndex("GepjarmuID");

                    b.HasIndex("SoforID");

                    b.ToTable("Fuvarok");

                    b.HasData(
                        new
                        {
                            FuvarID = 1,
                            BerakoCim = "5000 Szolnok, Kossuth utca 48.",
                            Feladat = "Bútorszállítás",
                            GepjarmuID = 1,
                            IndulasIdeje = new DateTime(2019, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "6726 Szeged, Szapolyai utca 37.",
                            SoforID = 2
                        },
                        new
                        {
                            FuvarID = 2,
                            BerakoCim = "5000 Szolnok, Szapáry utca 48.",
                            Feladat = "Hulladékszállítás",
                            GepjarmuID = 2,
                            IndulasIdeje = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "5000 Szolnok, Tulipán utca 48.",
                            SoforID = 6
                        },
                        new
                        {
                            FuvarID = 3,
                            BerakoCim = "7100 Szekszárd, Keselyűsi út 22.",
                            Feladat = "Áruszállítás",
                            GepjarmuID = 3,
                            IndulasIdeje = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "7100 Szekszárd, Alisca utca 22.",
                            SoforID = 2
                        },
                        new
                        {
                            FuvarID = 4,
                            BerakoCim = "6726 Szeged, Szentesi utca 37.",
                            Feladat = "Áruszállítás",
                            GepjarmuID = 4,
                            IndulasIdeje = new DateTime(2019, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "6726 Szeged, Várkonyi tér 37.",
                            SoforID = 6
                        },
                        new
                        {
                            FuvarID = 5,
                            BerakoCim = "5000 Szolnok, Szapáry utca 48.",
                            Feladat = "Személyszállítás",
                            GepjarmuID = 5,
                            IndulasIdeje = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "6726 Szeged, Várkonyi tér 37.",
                            SoforID = 3
                        },
                        new
                        {
                            FuvarID = 6,
                            BerakoCim = "7100 Szekszárd, Keselyűsi út 22.",
                            Feladat = "Csomagszállítás",
                            GepjarmuID = 6,
                            IndulasIdeje = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "6726 Szeged, Várkonyi tér 37.",
                            SoforID = 19
                        },
                        new
                        {
                            FuvarID = 7,
                            BerakoCim = "5000 Szolnok, Ady Endre utca 156.",
                            Feladat = "Csomagszállítás",
                            GepjarmuID = 7,
                            IndulasIdeje = new DateTime(2019, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "6726 Szeged, Várkonyi tér 37.",
                            SoforID = 11
                        },
                        new
                        {
                            FuvarID = 8,
                            BerakoCim = "6726 Szeged, Várkonyi tér 37.",
                            Feladat = "Áruszállítás",
                            GepjarmuID = 8,
                            IndulasIdeje = new DateTime(2019, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "5000 Szolnok, Kilián út 37.",
                            SoforID = 17
                        },
                        new
                        {
                            FuvarID = 9,
                            BerakoCim = "7100 Szekszárd, Keselyűsi út 22.",
                            Feladat = "Áruszállítás",
                            GepjarmuID = 9,
                            IndulasIdeje = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "5000 Szolnok, Kilián út 37.",
                            SoforID = 15
                        },
                        new
                        {
                            FuvarID = 10,
                            BerakoCim = "5000 Szolnok, Kilián út 37.",
                            Feladat = "Áruszállítás",
                            GepjarmuID = 10,
                            IndulasIdeje = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "5000 Szolnok, Nagy József út 37.",
                            SoforID = 16
                        },
                        new
                        {
                            FuvarID = 11,
                            BerakoCim = "6726 Szeged, Várkonyi tér 37.",
                            Feladat = "Személyszállítás",
                            GepjarmuID = 11,
                            IndulasIdeje = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "5000 Szolnok, Nagy József út 37.",
                            SoforID = 21
                        },
                        new
                        {
                            FuvarID = 12,
                            BerakoCim = "7100 Szekszárd, Keselyűsi út 22.",
                            Feladat = "Személyszállítás",
                            GepjarmuID = 12,
                            IndulasIdeje = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "6726 Szeged, Várkonyi tér 37.",
                            SoforID = 1
                        },
                        new
                        {
                            FuvarID = 13,
                            BerakoCim = "7100 Szekszárd, Keselyűsi út 22.",
                            Feladat = "Személyszállítás",
                            GepjarmuID = 13,
                            IndulasIdeje = new DateTime(2019, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "6726 Szeged, Várkonyi tér 37.",
                            SoforID = 3
                        },
                        new
                        {
                            FuvarID = 14,
                            BerakoCim = "5000 Szolnok, Nagy József út 37.",
                            Feladat = "Személyszállítás",
                            GepjarmuID = 14,
                            IndulasIdeje = new DateTime(2019, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "7100 Szekszárd, Keselyűsi út 22.",
                            SoforID = 19
                        },
                        new
                        {
                            FuvarID = 15,
                            BerakoCim = "6726 Szeged, Várkonyi tér 37.",
                            Feladat = "Csomagszállítás",
                            GepjarmuID = 15,
                            IndulasIdeje = new DateTime(2019, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "7100 Szekszárd, Keselyűsi út 22.",
                            SoforID = 19
                        },
                        new
                        {
                            FuvarID = 16,
                            BerakoCim = "6726 Szeged, Várkonyi tér 37.",
                            Feladat = "Áruszállítás",
                            GepjarmuID = 4,
                            IndulasIdeje = new DateTime(2019, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "7100 Szekszárd, Keselyűsi út 22.",
                            SoforID = 18
                        },
                        new
                        {
                            FuvarID = 17,
                            BerakoCim = "6726 Szeged, Várkonyi tér 37.",
                            Feladat = "Személyszállítás",
                            GepjarmuID = 5,
                            IndulasIdeje = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KirakoCim = "5000 Szolnok, Nagy József út 37.",
                            SoforID = 3
                        });
                });

            modelBuilder.Entity("WebDiszpecser.Models.Gepjarmu", b =>
                {
                    b.Property<int>("GepjarmuID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FutottKm");

                    b.Property<int>("Kategoria");

                    b.Property<string>("Rendszam")
                        .IsRequired();

                    b.Property<int>("SzervizCiklus");

                    b.Property<int>("TelephelyID");

                    b.Property<string>("Tipus")
                        .IsRequired();

                    b.Property<DateTime>("UtolsoSzerviz");

                    b.HasKey("GepjarmuID");

                    b.HasIndex("TelephelyID");

                    b.ToTable("Gepjarmuvek");

                    b.HasData(
                        new
                        {
                            GepjarmuID = 1,
                            FutottKm = 120000,
                            Kategoria = 1,
                            Rendszam = "FGH345",
                            SzervizCiklus = 30000,
                            TelephelyID = 1,
                            Tipus = "MB1017",
                            UtolsoSzerviz = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 2,
                            FutottKm = 124070,
                            Kategoria = 1,
                            Rendszam = "MNB123",
                            SzervizCiklus = 30000,
                            TelephelyID = 2,
                            Tipus = "MB1017",
                            UtolsoSzerviz = new DateTime(2019, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 3,
                            FutottKm = 65120,
                            Kategoria = 1,
                            Rendszam = "GKT786",
                            SzervizCiklus = 30000,
                            TelephelyID = 3,
                            Tipus = "Rába H14",
                            UtolsoSzerviz = new DateTime(2018, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 4,
                            FutottKm = 67120,
                            Kategoria = 1,
                            Rendszam = "GKJ786",
                            SzervizCiklus = 30000,
                            TelephelyID = 1,
                            Tipus = "Rába H14",
                            UtolsoSzerviz = new DateTime(2018, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 5,
                            FutottKm = 260120,
                            Kategoria = 2,
                            Rendszam = "HBJ786",
                            SzervizCiklus = 50000,
                            TelephelyID = 2,
                            Tipus = "Ikarusz 452",
                            UtolsoSzerviz = new DateTime(2019, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 6,
                            FutottKm = 100450,
                            Kategoria = 0,
                            Rendszam = "GKZ667",
                            SzervizCiklus = 30000,
                            TelephelyID = 3,
                            Tipus = "Mercedes Sprinter",
                            UtolsoSzerviz = new DateTime(2019, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 7,
                            FutottKm = 104450,
                            Kategoria = 0,
                            Rendszam = "GKZ657",
                            SzervizCiklus = 30000,
                            TelephelyID = 1,
                            Tipus = "Mercedes Sprinter",
                            UtolsoSzerviz = new DateTime(2018, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 8,
                            FutottKm = 570450,
                            Kategoria = 3,
                            Rendszam = "GTZ457",
                            SzervizCiklus = 50000,
                            TelephelyID = 2,
                            Tipus = "MAN 3220",
                            UtolsoSzerviz = new DateTime(2018, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 9,
                            FutottKm = 570580,
                            Kategoria = 3,
                            Rendszam = "RTU345",
                            SzervizCiklus = 50000,
                            TelephelyID = 3,
                            Tipus = "DAF 20",
                            UtolsoSzerviz = new DateTime(2017, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 10,
                            FutottKm = 540580,
                            Kategoria = 3,
                            Rendszam = "RTU785",
                            SzervizCiklus = 50000,
                            TelephelyID = 1,
                            Tipus = "DAF 20",
                            UtolsoSzerviz = new DateTime(2018, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 11,
                            FutottKm = 54580,
                            Kategoria = 0,
                            Rendszam = "GHU785",
                            SzervizCiklus = 15000,
                            TelephelyID = 2,
                            Tipus = "VW T6",
                            UtolsoSzerviz = new DateTime(2018, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 12,
                            FutottKm = 60580,
                            Kategoria = 0,
                            Rendszam = "GJU785",
                            SzervizCiklus = 15000,
                            TelephelyID = 3,
                            Tipus = "VW T6",
                            UtolsoSzerviz = new DateTime(2019, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 13,
                            FutottKm = 280580,
                            Kategoria = 0,
                            Rendszam = "DFU965",
                            SzervizCiklus = 15000,
                            TelephelyID = 1,
                            Tipus = "VW LT-4",
                            UtolsoSzerviz = new DateTime(2019, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 14,
                            FutottKm = 10580,
                            Kategoria = 0,
                            Rendszam = "LFU965",
                            SzervizCiklus = 30000,
                            TelephelyID = 2,
                            Tipus = "VW Golf Variant",
                            UtolsoSzerviz = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GepjarmuID = 15,
                            FutottKm = 150580,
                            Kategoria = 0,
                            Rendszam = "HJU895",
                            SzervizCiklus = 15000,
                            TelephelyID = 3,
                            Tipus = "Renault Jumper",
                            UtolsoSzerviz = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebDiszpecser.Models.Sofor", b =>
                {
                    b.Property<int>("SoforID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Csaladnev")
                        .IsRequired();

                    b.Property<DateTime>("Ervenyesseg");

                    b.Property<string>("JogositvanySzam")
                        .IsRequired();

                    b.Property<int>("Kategoria");

                    b.Property<string>("Keresztnev")
                        .IsRequired();

                    b.Property<DateTime>("SzulIdo");

                    b.HasKey("SoforID");

                    b.ToTable("Soforok");

                    b.HasData(
                        new
                        {
                            SoforID = 1,
                            Csaladnev = "Gulyás",
                            Ervenyesseg = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "1234EA",
                            Kategoria = 0,
                            Keresztnev = "János",
                            SzulIdo = new DateTime(1985, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 2,
                            Csaladnev = "Csukás",
                            Ervenyesseg = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "2143SD",
                            Kategoria = 1,
                            Keresztnev = "Géza",
                            SzulIdo = new DateTime(1975, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 3,
                            Csaladnev = "Borsfalvy",
                            Ervenyesseg = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "5476VC",
                            Kategoria = 2,
                            Keresztnev = "Győző",
                            SzulIdo = new DateTime(1984, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 4,
                            Csaladnev = "Kiss",
                            Ervenyesseg = new DateTime(2024, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "5786VL",
                            Kategoria = 3,
                            Keresztnev = "Márton",
                            SzulIdo = new DateTime(1983, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 5,
                            Csaladnev = "Nagy",
                            Ervenyesseg = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "6586BL",
                            Kategoria = 0,
                            Keresztnev = "Béla",
                            SzulIdo = new DateTime(1973, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 6,
                            Csaladnev = "Boros",
                            Ervenyesseg = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "6126FL",
                            Kategoria = 1,
                            Keresztnev = "Béla",
                            SzulIdo = new DateTime(1987, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 7,
                            Csaladnev = "Mézga",
                            Ervenyesseg = new DateTime(2024, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "3698FL",
                            Kategoria = 1,
                            Keresztnev = "Géza",
                            SzulIdo = new DateTime(1980, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 8,
                            Csaladnev = "Mézga",
                            Ervenyesseg = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "3789GL",
                            Kategoria = 1,
                            Keresztnev = "Aladár",
                            SzulIdo = new DateTime(1989, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 9,
                            Csaladnev = "Sziráki",
                            Ervenyesseg = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "3129GL",
                            Kategoria = 1,
                            Keresztnev = "József",
                            SzulIdo = new DateTime(1989, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 10,
                            Csaladnev = "Döbrögi",
                            Ervenyesseg = new DateTime(2024, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "3544GL",
                            Kategoria = 1,
                            Keresztnev = "József",
                            SzulIdo = new DateTime(1978, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 11,
                            Csaladnev = "Ludas",
                            Ervenyesseg = new DateTime(2021, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "3544GL",
                            Kategoria = 0,
                            Keresztnev = "Mátyás",
                            SzulIdo = new DateTime(1978, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 12,
                            Csaladnev = "Martonyi",
                            Ervenyesseg = new DateTime(2021, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "8844KL",
                            Kategoria = 0,
                            Keresztnev = "István",
                            SzulIdo = new DateTime(1976, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 13,
                            Csaladnev = "Békési",
                            Ervenyesseg = new DateTime(2021, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "8844KL",
                            Kategoria = 3,
                            Keresztnev = "Bertold",
                            SzulIdo = new DateTime(1979, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 14,
                            Csaladnev = "Márkus",
                            Ervenyesseg = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "8845GH",
                            Kategoria = 3,
                            Keresztnev = "Iván",
                            SzulIdo = new DateTime(1979, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 15,
                            Csaladnev = "Meggyesi",
                            Ervenyesseg = new DateTime(2020, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "3445GH",
                            Kategoria = 3,
                            Keresztnev = "Ödön",
                            SzulIdo = new DateTime(1979, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 16,
                            Csaladnev = "Bajai",
                            Ervenyesseg = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "2045GH",
                            Kategoria = 3,
                            Keresztnev = "Zoltán",
                            SzulIdo = new DateTime(1981, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 17,
                            Csaladnev = "Mészöly",
                            Ervenyesseg = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "2885GH",
                            Kategoria = 3,
                            Keresztnev = "Tibor",
                            SzulIdo = new DateTime(1981, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 18,
                            Csaladnev = "Vágó",
                            Ervenyesseg = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "9985GH",
                            Kategoria = 1,
                            Keresztnev = "Botond",
                            SzulIdo = new DateTime(1987, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 19,
                            Csaladnev = "Borkodi",
                            Ervenyesseg = new DateTime(2023, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "9977GH",
                            Kategoria = 0,
                            Keresztnev = "Olivér",
                            SzulIdo = new DateTime(1988, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 20,
                            Csaladnev = "Vörös",
                            Ervenyesseg = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "9117GH",
                            Kategoria = 1,
                            Keresztnev = "Dávid",
                            SzulIdo = new DateTime(1990, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SoforID = 21,
                            Csaladnev = "Várkonyi",
                            Ervenyesseg = new DateTime(2021, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JogositvanySzam = "9447GH",
                            Kategoria = 1,
                            Keresztnev = "Emil",
                            SzulIdo = new DateTime(1991, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebDiszpecser.Models.Telephely", b =>
                {
                    b.Property<int>("TelephelyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TelephelyCim")
                        .IsRequired();

                    b.HasKey("TelephelyID");

                    b.ToTable("Telephelyek");

                    b.HasData(
                        new
                        {
                            TelephelyID = 1,
                            TelephelyCim = "6726 Szeged, Bécsi körút 21."
                        },
                        new
                        {
                            TelephelyID = 2,
                            TelephelyCim = "5000 Szolnok, Ady Endre utca 156."
                        },
                        new
                        {
                            TelephelyID = 3,
                            TelephelyCim = "7100 Szekszárd, Keselyűsi út 22."
                        });
                });

            modelBuilder.Entity("WebDiszpecser.Models.Fuvar", b =>
                {
                    b.HasOne("WebDiszpecser.Models.Gepjarmu", "Gepjarmu")
                        .WithMany("Fuvarok")
                        .HasForeignKey("GepjarmuID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebDiszpecser.Models.Sofor", "Sofor")
                        .WithMany("Fuvarok")
                        .HasForeignKey("SoforID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebDiszpecser.Models.Gepjarmu", b =>
                {
                    b.HasOne("WebDiszpecser.Models.Telephely", "Telephely")
                        .WithMany("Gepjarmuvek")
                        .HasForeignKey("TelephelyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
